run-name: Testing ${{ github.actor }}'s PR!
name: C/C++ Build CI Check

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make debug
      run: make debug
    - name: make release
      run: make release
    - name: make clean
      run: make clean